[project]
name = "soulx-podcast"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "huggingface-hub>=1.3.4",
    "s3tokenizer>=0.3.0",
    "soundfile>=0.13.1",
    "torch>=2.10.0",
]
